default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: superplate_development

test:
  <<: *default
  database: superplate_test

production:
  <<: *default
  database: superplate_production
  username: superplate
  password: <%= ENV['superplate_DATABASE_PASSWORD'] %>
